/* $OpenBSD: version.h,v 1.66 2013/02/10 21:19:34 markus Exp $ */

#define SSH_VERSION	"OpenSSH_6.2"

#define SSH_PORTABLE	"p1"
#define SSH_HPN		"-hpn13v12"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_HPN

#ifdef NERSC_MOD
#undef SSH_RELEASE
#define SSH_AUDITING	"NMOD_3.11"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_AUDITING SSH_HPN
#endif /* NERSC_MOD */
